### PR TITLE
Correcting Toolchain-README-ko file  

### PR DESCRIPTION
**Pull request by hisunah**
Correcting Toolchain-README-ko file

### CODE REVIEW

**Comment by svennam92** [comment]
hi @hisunah, changes look good but could you resolve the merge conflicts?

**Comment by hisunah** [comment]
hi Sai, there's no conflict as far as I've checked the file and I do not have write access to this repository. 

kakaotalk_photo_2017-07-28-14-47-51

**Comment by hisunah** [comment]
@svennam92  I see you added some image files in APIC-ERP-README file, do you want me to update APIC-ERP-README-ko? Otherwise, there's no conflict..

**Comment by svennam92** [comment]
Here's what I'm seeing when trying to merge:
image
Could you try pulling the latest changes to master?

**Comment by jgkong** [comment]
Since this changes made before pulling from upstream, PR cannot be rebased. Would you try Squash and merge this PR? It will also remove unnecessary commits.

**Pull request merged**
